version: 2.1
orbs: 
  snyk: snyk/snyk@1.1.2

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
  snyk-scan:
    docker:
      - image: cimg/openjdk:11.0-node
    steps:
      - checkout
      - run:
          name: Install Snyk to HTML
          command: npm install --prefix=$HOME/.local -g snyk-to-html
      - snyk/scan:
          monitor-on-build: false
          fail-on-issues: false
          command: code test
          additional-arguments: --json-file-output=code-results.json
      - run:
          name: Generate Snyk HTML report
          command: cat code-results.json | snyk-to-html -o code-report.html
      - store_artifacts:
          path: code-report.html

workflows:
  build-test-snyk:
    jobs:
      - build-and-test
      - snyk-scan
