
image: maven:3-jdk-11

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - maven
        script:
          - mvn install
          - curl -sL https://deb.nodesource.com/setup_10.x | bash -
          - apt-get -y upgrade
          - apt-get -y install nodejs
          - apt-get -y install npm
          - npm install -g snyk
          - npm install snyk-to-html -g
          - snyk auth $SNYK_TOKEN
          - snyk test --json | snyk-to-html -o snyk_results.html

        artifacts:
          download: true
          paths:
            - snyk_results.html