version: 0.2

env:
  parameter-store:
    # Requires that you have a secure string in AWS Systems Manager Parameter Store
    # called "snykAuthToken" with your Snyk token.
    SNYK_TOKEN: "snykAuthToken"

phases:
  install:
    commands:
      # Use this if you just want to use a fixed version:
#      - curl -Lo ./snyk "https://github.com/snyk/snyk/releases/download/v1.136.3/snyk-linux"

      # Use this to always get the latest version:
      - latest_version=$(curl -Is "https://github.com/snyk/snyk/releases/latest" | grep -i "Location" | sed s#.*tag/##g | tr -d "\r")
      - snyk_cli_dl_linux="https://github.com/snyk/snyk/releases/download/${latest_version}/snyk-linux"
      - curl -Lo ./snyk $snyk_cli_dl_linux

      - chmod -R +x ./snyk

  build:
    commands:
      - npm install
      - npm test  # Run your unit tests, etc
      - ./snyk test
      - ./snyk monitor --org=<your-snyk-org-id>

#artifacts:
#files:
# - location
# - location
#name: $(date +%Y-%m-%d)
#discard-paths: yes
#base-directory: location
#cache:
#paths:
# - paths
