# Example for a Java Gradle Application using Snyk Gradle-Plugin
image: gradle:slim

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon-false"

before_script:
  - export GRADLE_USER

stages:
  - build
  - test
  - snyktest

build:
  stage: build
  script: ./gradlew --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  stage: test
  script: ./gradlew check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

snyktest:
  stage: snyktest
  script: gradle snyk-monitor
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
